version: '3'
services:
  client:
    build: ./client
    ports: 
      - '8000:3000'
    depends_on:
      - backend
    stdin_open: true
  backend:
    build: ./backend
    ports:
      - '8001:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports: 
      - '27017:27017'